name: arna_logger
description: A pretty logger for your applications.
homepage: https://github.com/MahanRahmati/arna_logger
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
