name: arna_logger
description: Arna Logger is a small and pretty logger for your applications.
homepage: https://github.com/MahanRahmati/arna_logger
version: 1.1.0
topics:
  - logger
  - log

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
